/**
 * Script to generate TaskTemplateId type from the task templates JSON.
 * Run with: bun run scripts/generate-task-types.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

interface TaskTemplate {
  id: string;
  name: string;
  description: string;
  frequency: string;
  department: string;
}

const TASK_TEMPLATES_PATH = join(
  __dirname,
  '../../../packages/db/prisma/seed/primitives/FrameworkEditorTaskTemplate.json',
);

const OUTPUT_PATH = join(__dirname, '../src/task-mappings.ts');

function generateTaskTypes() {
  // Read the JSON file
  const jsonContent = readFileSync(TASK_TEMPLATES_PATH, 'utf-8');
  const tasks: TaskTemplate[] = JSON.parse(jsonContent);

  // Generate the TypeScript file
  const lines: string[] = [
    '// ============================================================================',
    '// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY',
    '// Generated by: bun run scripts/generate-task-types.ts',
    '// ============================================================================',
    '',
    '/**',
    ' * All available task template IDs that can be used for task mapping.',
    ' * These are derived from the FrameworkEditorTaskTemplate seed data.',
    ' */',
    'export const TASK_TEMPLATE_IDS = [',
  ];

  // Add each task ID as a const
  for (const task of tasks) {
    lines.push(`  '${task.id}', // ${task.name}`);
  }

  lines.push('] as const;');
  lines.push('');
  lines.push('/**');
  lines.push(' * Union type of all valid task template IDs.');
  lines.push(' * Use this for type-safe task mapping in integration checks.');
  lines.push(' */');
  lines.push('export type TaskTemplateId = (typeof TASK_TEMPLATE_IDS)[number];');
  lines.push('');

  // Add a mapping object for easy lookup by name
  lines.push('/**');
  lines.push(' * Mapping of task names to their IDs for easier reference.');
  lines.push(' * Use this when you know the task name but need the ID.');
  lines.push(' */');
  lines.push('export const TASK_TEMPLATES = {');

  // Task names that do not derive a usable identifier, or whose derived key
  // callers already depend on. Keyed by task name so a rename shows up here
  // as an obvious miss rather than silently breaking every call site.
  const KEY_OVERRIDES: Record<string, string> = {
    // "2FA" would derive `2fa`, which is not a valid identifier. Existing
    // checks and the two-factor-source controller import `twoFactorAuth`.
    '2FA': 'twoFactorAuth',
  };

  // Two task templates can share a name (e.g. an ISO and a QMS "Management
  // Review Minutes"), which would emit a duplicate object key and fail to
  // compile. First occurrence wins; later ones are recorded as a comment so
  // the collision is visible rather than silent. Every id is still reachable
  // through TASK_TEMPLATE_IDS above.
  const seenKeys = new Map<string, string>();

  for (const task of tasks) {
    // Convert name to a valid JS identifier (camelCase, no special chars)
    const derived = task.name
      .replace(/[^a-zA-Z0-9\s]/g, '')
      .split(/\s+/)
      .filter(Boolean)
      .map((word, i) =>
        i === 0 ? word.toLowerCase() : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase(),
      )
      .join('');

    const key = KEY_OVERRIDES[task.name.trim()] ?? derived;
    if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)) {
      throw new Error(
        `Task "${task.name}" (${task.id}) derives the invalid identifier "${key}". ` +
          `Add an entry to KEY_OVERRIDES in scripts/generate-task-types.ts.`,
      );
    }

    const existingId = seenKeys.get(key);
    if (existingId) {
      console.warn(
        `Duplicate task name "${task.name}": keeping ${existingId}, skipping ${task.id}`,
      );
      lines.push(`  // ${task.id} also maps to "${key}" — use the id directly`);
      continue;
    }
    seenKeys.set(key, task.id);

    lines.push(`  /** ${task.name} */`);
    lines.push(`  ${key}: '${task.id}',`);
  }

  lines.push('} as const;');
  lines.push('');

  // Add a reverse mapping for getting task info by ID
  lines.push('/**');
  lines.push(' * Task template metadata for reference.');
  lines.push(' */');
  lines.push('export const TASK_TEMPLATE_INFO: Record<');
  lines.push('  TaskTemplateId,');
  lines.push('  { name: string; description: string; department: string; frequency: string }');
  lines.push('> = {');

  // Escape a value for embedding inside a single-quoted TS string literal.
  // Backslash MUST be escaped first, otherwise the quote-escaping is incomplete
  // (e.g. a trailing "\" or "\'" would break out of the literal).
  const sq = (value: string) => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

  for (const task of tasks) {
    // Escape description for use in a template literal (backslash first).
    const escapedDesc = task.description
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$/g, '\\$')
      .substring(0, 100); // Truncate for readability

    lines.push(`  ${sq(task.id)}: {`);
    lines.push(`    name: ${sq(task.name)},`);
    lines.push(`    description: \`${escapedDesc}...\`,`);
    lines.push(`    department: ${sq(task.department)},`);
    lines.push(`    frequency: ${sq(task.frequency)},`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  // Write the output file
  writeFileSync(OUTPUT_PATH, lines.join('\n'));
  console.log(`✅ Generated ${OUTPUT_PATH}`);
  console.log(`   ${tasks.length} task templates`);
}

generateTaskTypes();
